language: cpp

compiler:
  - gcc

before_install:
  - git submodule update --init --recursive

before_script:
  - chmod +x test/run

script:
  - autoreconf --install
  - ./configure
  - make test

branches:
  only:
    - master
