language: cpp

compiler:
  - gcc

branches:
  only:
    - master

sudo: false

before_install:
  - git submodule update --init --recursive

install:
  - autoreconf -fiv
  - ./configure --prefix=$HOME/build

script:
  - make all test install
